added feature login with username
Webmasters-Europe/codemeetup-forum pull request #27
Opened 2021-02-09 16:40 UTC by milack68

2021-02-12 21:03 UTC, Cosnavel requested changes
@milack68 ich würde den Mamp Installer ungern im Projekt haben. Kannst du den in deine .gitignore hinzufügen. Dann kannst du den lokal verwenden. Er wird aber nicht ins Projekt gepusht.

2021-02-13 09:16 UTC, milack68 commented
> @milack68 ich würde den Mamp Installer ungern im Projekt haben. Kannst du den in deine .gitignore hinzufügen. Dann kannst du den lokal verwenden. Er wird aber nicht ins Projekt gepusht.

erledigt.

2021-02-13 11:56 UTC, Cosnavel approved these changes
✅

2021-02-13 11:58 UTC, merged

2021-02-13 12:00 UTC, Cosnavel commented
Close #22