Feature o auth with google
Webmasters-Europe/codemeetup-forum pull request #32
Opened 2021-02-14 16:59 UTC by milack68

Added Feature oAuth with google (issue #18):
- installed Package Socialite
- if there is no username saved in the Google-Account username will set to value of name-field
- if there is no name saved in the Google-Account name will set to value of username-field
- all functions can used with other oAuth-Logins (e.g. Github, Facebook, Twitter, ...):
  - only edit config/services.php, .env-file and link in view

2021-02-15 23:05 UTC, Cosnavel requested changes
Sieht soweit gut aus. Kannst du die Kleinigkeiten der Kommentare resolven? Dann können wir das rein mergen.

2021-02-15 23:05 UTC, Cosnavel commented on config/services.php
> +    ],
Kannst du Beispieldaten in der .env.example nachziehen?

2021-02-15 23:06 UTC, Cosnavel commented
Ah ja @milack68 bitte bringe deine Branch noch auf aktuellen Stand, sodass wir keine Merge Konflikte mehr haben.

2021-02-16 16:24 UTC, milack68 commented
Habe Änderungen vorgenommen. Bitte Code reviewen.

2021-02-16 16:40 UTC, Cosnavel approved these changes

2021-02-16 16:41 UTC, Cosnavel commented
@milack68 löst du die Konflikte auf oder soll ich das machen ?

2021-02-16 16:45 UTC, milack68 commented
> @milack68 löst du die Konflikte auf oder soll ich das machen ?

Ich verstehe nicht, warum hier überhaupt so viele Konflikte vorhanden sind. php_cs.cache habe ich noch nie angerührt, auch package-lock.json nicht. Gitignore dachte ich hätte ich bereits beim letzten Mal aufgelöst und den RegisterController habe ich auch nicht geändert.

2021-02-16 17:04 UTC, merged

2021-02-16 17:21 UTC, RheaMarst commented
> > @milack68 löst du die Konflikte auf oder soll ich das machen ?
> 
> Ich verstehe nicht, warum hier überhaupt so viele Konflikte vorhanden sind. php_cs.cache habe ich noch nie angerührt, auch package-lock.json nicht. Gitignore dachte ich hätte ich bereits beim letzten Mal aufgelöst und den RegisterController habe ich auch nicht geändert.

@milack68 Das mit dem RegisterController war ich - da hatte ich die doppelten use-Statements entfernt und du hattest vermutlich nicht den aktuellen Stand vom main-Branch, als du mit dem oAuth-Ticket losgelegt hast. Die package-lock.json verändert sich immer automatisch, wenn du über npm oder yarn neue Packages installiert, wenn sich also die package.json verändert.