Code Update 21.02.2021 createPost.html
Webmasters-Europe/codemeetup-forum pull request #48
Opened 2021-02-21 11:48 UTC by Klingohle

#47 Issue Closed

2021-02-21 11:49 UTC, thelf approved these changes

2021-02-21 12:07 UTC, thelf requested changes
Ich kann die neuen Dateien die wir angelegt haben nicht sehen, ist das bei euch auch so?

2021-02-21 12:27 UTC, alenavershinina commented
> Ich kann die neuen Dateien die wir angelegt haben hier im Pull Request nicht sehen, ist das bei euch auch so? Ok Denkfehler, die Datei wurde ja neu erstellt und hat keine Änderungen, jetzt sehe ich sie auch.

Ja, in file changes sehe ich "97,881 additions, 0 deletions not shown because the diff is too large. Please use a local Git client to view these changes." Und ich habe kein local Git client installiert

2021-02-21 15:26 UTC, thelf approved these changes

2021-02-21 19:06 UTC, thelf approved these changes

2021-02-22 07:50 UTC, alenavershinina approved these changes

2021-02-24 14:59 UTC, thelf approved these changes

2021-02-24 17:29 UTC, Cosnavel approved these changes

2021-02-24 17:30 UTC, merged